#!/bin/sh

set -e
. "$(dirname "$0")/.common.sh"

dpkg --add-architecture i386

curl -s "$repo_key_url" | gpg --dearmor >/etc/apt/trusted.gpg.d/wine.gpg

echo "deb $deb_repo $dist main" >/etc/apt/sources.list.d/wine.list

cat >/etc/apt/preferences.d/latest-build-tools <<EOF
Package: debhelper dwz meson
Pin: origin *
Pin-Priority: 990
EOF

apt-get -o APT::Get::List-Cleanup=false update
apt-get -y upgrade

cp /var/lib/dpkg/status "$dpkg_status_save"
