#!/bin/sh

set -e
. "$(dirname "$0")/.common.sh"

dpkg --add-architecture i386

cat >/etc/apt/preferences.d/latest-build-tools <<EOF
Package: debhelper dwz meson
Pin: origin *
Pin-Priority: 990
EOF

apt-get -o APT::Get::List-Cleanup=false update
apt-get -y upgrade

cp /var/lib/dpkg/status "$dpkg_status_save"
