#!/bin/sh

: ${lbu:=/opt/LiveBootUtils}
: ${dist:=$(lsb_release -cs)}

set -e

dpkg --add-architecture i386

curl -s https://dl.winehq.org/wine-builds/Release.key | apt-key add -

echo "deb https://dl.winehq.org/wine-builds/debian/ $dist main" >/etc/apt/sources.list.d/wine.list

apt-get -o APT::Get::List-Cleanup=false update
apt-get -y upgrade

"$lbu/scripts/apt-sfs.sh" "$DESTDIR" winehq-stable
