#!/bin/sh

set -e
. "$(dirname "$0")/.common.sh"

pkg_name="faudio"
build_i386="1"

: "${src_repo:=http://cdn.debian.net/debian testing main contrib non-free}"
: "${deb_build_dir:=/usr/src/deb}"

echo "deb-src $src_repo" >/etc/apt/sources.list.d/build-sources.list
apt-get update

mkdir -p "$deb_build_dir"
cd "$deb_build_dir"

apt-get -y build-dep "$pkg_name"
apt-get -y source --compile "$pkg_name"

if test -n "$build_i386";then
pkg_src_dir="$(find "$deb_build_dir" -mindepth 1 -maxdepth 1 -type d -name "${pkg_name}-*" | sort -n | tail -1)"
apt-get -y install crossbuild-essential-i386
apt-get -y build-dep -a i386 "$pkg_name"

( cd "$pkg_src_dir"; dpkg-buildpackage -a i386 -b -uc )
fi

dpkg-scanpackages --multiversion . >Packages

echo "deb [trusted=yes] file://$deb_build_dir ./" >/etc/apt/sources.list.d/usr-src-deb.list
deb_build_lst_name="$(echo "$deb_build_dir/./Packages" | tr / _)"
test -L "/var/lib/apt/lists/$deb_build_lst_name" ||
  ln -vfs "$deb_build_dir"/Packages "/var/lib/apt/lists/$deb_build_lst_name"
