#!/bin/sh

set -e
. "$(dirname "$0")/.common.sh"

: "${wine_rec_i386:=$(grep ^Recommends: $(find "$DESTDIR/var/lib/dpkg/info" -name "wine*-i386.control") | cut -f2 -d: | tr , '\n' | tr -d ' ' | awk '{print $1 ":i386"}' | grep -vxEe "$rec_ignore")}"
: "${wine_rec_amd64:=$(grep ^Recommends: $(find "$DESTDIR/var/lib/dpkg/info" -name "wine*-amd64.control") | cut -f2 -d: | tr , '\n' | tr -d ' ' | awk '{print $1}' | grep -vxEe "$rec_ignore")}"

"$lbu/scripts/apt-sfs.sh" "$DESTDIR" $wine_rec_i386 $wine_rec_amd64
